---

- hosts: localhost
  become: yes
  tasks:
  - name: Install python, pip and git
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: true
    with_items:
      - python
      - python3
      - python3-pip
      - git
      - libasound-dev
      - portaudio19-dev
      - libportaudio2
      - libportaudiocpp0

  - name: Install chrome
    block:
    - name: "apt | ensure Google linux signing key present"
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

    - name: "apt | ensure Google chrome repo present"
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        filename: "google-chrome"
        state: present
        update_cache: yes

    - name: Update apt cache
      apt: update_cache=true


    - name: Install chrome
      apt:
        pkg: google-chrome-stable
        state: installed

    - name: Set chrome as default browser
      command: xdg-settings set default-web-browser google-chrome.desktop

  - name: Delete any old directory from teleserver
    file:
      path: /usr/local/teleserver
      state: absent

  - name: Pull files
    git:
      repo: 'https://github.com/Dysproz/teleserver.git'
      dest: /usr/local/teleserver

  - name: Set permission for directory
    file:
      state: directory
      path: "/usr/local/teleserver"
      mode: 0777
      recurse: yes

  - name: Install required modules
    pip:
      requirements: "/usr/local/teleserver/requirements.txt"
      executable: pip3

  - name: Find username
    command: who
    register: username

  - name: Add startup command to bashrc
    lineinfile:
      path: "/home/{{ (username.stdout_lines[0].split())[0] }}/.profile"
      state: present
      line: nohup python3 /usr/local/teleserver/run.py &

  - name: Turn off auto screen lock
    shell: gsettings set org.gnome.desktop.screensaver lock-enabled false

  - name: Reboot
    command: reboot
