---

- hosts: localhost
  become: yes
  tasks:
  - name: Clear directory
    file:
      state: absent
      path: "/usr/local/teleserver/"

  - name: Create empty teleserver directory
    file:
      state: directory
      path: "/usr/local/teleserver"

  - name: Pull files
    git:
      repo: 'https://github.com/Dysproz/teleserver.git'
      dest: /usr/local/teleserver
  
  - name: Set permission 
    file:
      state: directory
      path: "/usr/local/teleserver"
      mode: 0777
      recurse: yes

  - name: Reboot
    command: reboot
