---

- hosts: localhost
  become: yes
  tasks:
  - name: Install python, pip, git and supervisor
    become: yes
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: true
    with_items:
      - python
      - python3
      - python-pip
      - git
      

  - name: Install flask and wtforms
    pip:
      name: "{{ item }}"
    with_items:
      - flask
      - wtforms
  - name: Install chrome
    become: yes
    block:
    - name: "apt | ensure Google linux signing key present"
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
          
    - name: "apt | ensure Google chrome repo present"
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        filename: "google-chrome"
        state: present
        update_cache: yes
    
    - name: Update apt cache
      become: yes
      apt: update_cache=true
      

    - name: Install chrome
      become: yes
      apt:
        pkg: google-chrome-stable
        state: installed
        
    - name: Set chrome as default browser
      become: yes
      command: xdg-settings set default-web-browser google-chrome.desktop

  - name: Pull files
    git:
      repo: 'https://github.com/Dysproz/FlaskTVRemote.git'
      dest: /usr/local/teleserver
  
  - name: Find username
    command: whoami
    register: username
    
  - name: Check for rc.local file
    stat:
      path: /etc/rc.local
    register: rc_local_stat

  - name: If file doesn't exist
    block:
    - name: Create file
      file:
        path: /etc/rc.local
        state: touch

    - name: Add lines
      lineinfile:
        path: /etc/rc.local
        state: present
        line: "{{ item }}"
      with_items:
        - '#!/bin/sh'
        - "su {{ username }} -c 'python /usr/local/teleserver/run.py'"
        - exit 0
  when: rc_local_stat == False

  - name: If file exists
    block:
    - name: remove exit 0 line
      lineinfile:
        path: /etc/rc.local
        state: absent
        line: exit 0

    - name: Add lines
      lineinfile:
        path: /etc/rc.local
        state: present
        line: "{{ item }}"
      with_items:
        - "su {{ username }} -c 'python /usr/local/teleserver/run.py'"
        - 'exit 0'

  when: rc_local_stat == True

  - name: Reboot
    command: reboot
  

        