---

- hosts: localhost
  become: yes
  tasks:
  - name: Install python, pip, git and supervisor
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: true
    with_items:
      - python
      - python3
      - python-pip
      - git
      - supervisor

  - name: Install flask and wtforms
    pip:
      name: "{{ item }}"
    with_items:
      - flask
      - wtforms
  - name: Install chrome
    block:
    - name: Check for chrome
      command: test -f /etc/apt/sources.list.d/google-chrome.list
      register: google_apt_exists
      ignore_errors: True

    - name: Add google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1

    - name: Update apt cache
      apt: update_cache=yes
      when: google_apt_exists.rc == 1

    - name: Install chrome
      apt:
        pkg: google-chrome-stable
        state: installed
        
  - name: Pull files
    git:
      repo: 'https://github.com/Dysproz/FlaskTVRemote.git'
      dest: /usr/local/teleserver

  - name: Configure teleserver to autostart
    block:
    - name: Copy configuration file to supervisor
      copy:
        src: /usr/local/teleserver/teleserver.conf
        dest: /etc/supervisor/conf.d/teleserver.conf
        
    - name: Reread supervisor
      command: supervisorctl reread

    - name: Update supervisor
      command: supervisorctl update

  - name: Reboot
    command: reboot
  

        