---

- hosts: localhost
  become: yes
  tasks:
  - name: Install python and pip
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: true
    with_items:
      - python
      - python3
      - python-pip
      - git
      - supervisor

  - name: Install flask and wtforms
    pip:
      name: "{{ item }}"
    with_items:
      - Flask
      - wtforms
    
  - name: Pull files
    git:
      repo: 'https://github.com/Dysproz/FlaskTVRemote.git'
      dest: /usr/local/teleserver

  - name: Configure teleserver to autostart
    block:
    - name: Copy configuration file to supervisor
      copy:
        src: /usr/local/teleserver/teleserver.conf
        dest: /etc/supervisor/conf.d/teleserver.conf
        
    - name: Reread supervisor
      command: supervisorctl reread

    - name: Update supervisor
      command: supervisorctl update

  - name: Reboot
    command: reboot
  

        