---

- hosts: localhost
  become: yes
  tasks:
  - name: Find username
    command: who
    register: username

  - name: Create profile file without teleserver autorun
    shell: "grep -vwE 'teleserver' /home/{{ (username.stdout_lines[0].split())[0] }}/.profile > /home/{{ (username.stdout_lines[0].split())[0] }}/.profile_new"

  - name: Copy new profile configuration to .profile
    copy:
      src: "/home/{{ (username.stdout_lines[0].split())[0] }}/.profile_new"
      dest: "/home/{{ (username.stdout_lines[0].split())[0] }}/.profile"

  - name: Remove .profile_new
    file:
      state: absent
      path: "/home/{{ (username.stdout_lines[0].split())[0] }}/.profile_new"

  - name: Kill teleserver process
    shell: pkil -f teleserver

  - name: Turn on auto screen lock
    shell: gsettings set org.gnome.desktop.screensaver lock-enabled true

  - name: Remove teleserver files
    file:
      state: absent
      path: /usr/local/teleserver
    ignore_errors: yes



  