version: 2
jobs:
  tox:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install tox flake8 --user
            tox
    working_directory: ~/repo
workflows:
  version: 2
  tox_test:
    jobs:
      - tox
